import Head from "next/head";
import Image from "next/image";
import Features from "../components/Feature";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import NewsLetter from "../components/Newsletter";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      <Features/>
      <NewsLetter/>
      <Footer/>
    </>
  );
}
